services:

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports: 
      - 27017:27017
    networks:
      - twtrnetwork
  
  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mongodb://db:27017/
    depends_on:
      - db
    networks:
      - twtrnetwork

  fe:
    build:
      context: ./fe
      args:
        - NODE_ENV=development
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - REACT_APP_API_SERVICE_URL=http://be:5000
    depends_on:
      - be
    networks:
      - twtrnetwork

networks:
  twtrnetwork:
    driver: bridge
