# VERSION IS OBSOLETE
# see here https://docs.docker.com/compose/compose-file/compose-versioning/
# version: '3.1'

services:

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports: 
      - 27017:27017
    networks:
      - backend

  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - DATABASE_TEST_URL=mongodb://db:27017/
    networks:
      - backend

  fe:
    stdin_open: true
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - NODE_ENV=development
      - REACT_APP_BE_NETWORK=backend
      - REACT_APP_BE_PORT=5000
      - REACT_APP_API_SERVICE_URL=${REACT_APP_API_SERVICE_URL}
    depends_on:
      - be
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
